"""
Schemas for critique reports and related data structures.

These schemas define the structure of critiques generated by the critic system,
including identified flaws, edge cases, and contradictions.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional


class CritiqueSeverity(str, Enum):
    """Severity levels for critique issues."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


@dataclass
class EdgeCase:
    """
    An identified edge case that may not be handled correctly by a rule.

    Edge cases are specific scenarios that test the boundaries or limits
    of a rule's applicability.
    """

    description: str
    """Human-readable description of the edge case"""

    scenario: Dict[str, Any]
    """Structured representation of the scenario (facts, conditions, etc.)"""

    expected_outcome: Optional[str] = None
    """What should happen in this edge case"""

    current_outcome: Optional[str] = None
    """What actually happens with the current rule"""

    severity: CritiqueSeverity = CritiqueSeverity.MEDIUM
    """How critical is this edge case"""


@dataclass
class Contradiction:
    """
    A detected contradiction between a new rule and existing rules.

    Contradictions occur when rules produce conflicting conclusions
    for the same input.
    """

    description: str
    """Human-readable description of the contradiction"""

    new_rule: str
    """The proposed rule causing the contradiction"""

    conflicting_rule: str
    """The existing rule that conflicts"""

    example_scenario: Dict[str, Any]
    """A scenario that demonstrates the contradiction"""

    severity: CritiqueSeverity = CritiqueSeverity.HIGH
    """How serious is this contradiction"""

    resolution_suggestion: Optional[str] = None
    """Suggested way to resolve the contradiction"""


@dataclass
class CritiqueIssue:
    """
    A specific issue identified in a rule critique.

    Issues can be logical flaws, missing conditions, overly broad
    or narrow applicability, or other problems.
    """

    category: str
    """Type of issue (e.g., 'logical_flaw', 'missing_condition', 'too_broad')"""

    description: str
    """Detailed description of the issue"""

    location: Optional[str] = None
    """Where in the rule the issue occurs (if applicable)"""

    severity: CritiqueSeverity = CritiqueSeverity.MEDIUM
    """How critical is this issue"""

    suggestion: Optional[str] = None
    """Suggested fix or improvement"""


@dataclass
class CritiqueReport:
    """
    Comprehensive critique of a proposed rule.

    Contains all identified issues, edge cases, contradictions,
    and recommendations for improvement.
    """

    rule: str
    """The rule being critiqued"""

    issues: List[CritiqueIssue] = field(default_factory=list)
    """List of identified issues"""

    edge_cases: List[EdgeCase] = field(default_factory=list)
    """List of identified edge cases"""

    contradictions: List[Contradiction] = field(default_factory=list)
    """List of contradictions with existing rules"""

    overall_severity: CritiqueSeverity = CritiqueSeverity.LOW
    """Maximum severity across all issues"""

    recommendation: Optional[str] = None
    """Overall recommendation (accept, revise, reject)"""

    suggested_revision: Optional[str] = None
    """Suggested improved version of the rule"""

    confidence: float = 0.5
    """Confidence in the critique (0.0-1.0)"""

    timestamp: datetime = field(default_factory=datetime.now)
    """When the critique was generated"""

    metadata: Dict[str, Any] = field(default_factory=dict)
    """Additional metadata about the critique"""

    def has_critical_issues(self) -> bool:
        """Check if any issues are critical severity."""
        return (
            self.overall_severity == CritiqueSeverity.CRITICAL
            or any(i.severity == CritiqueSeverity.CRITICAL for i in self.issues)
            or any(c.severity == CritiqueSeverity.CRITICAL for c in self.contradictions)
        )

    def has_high_severity_issues(self) -> bool:
        """Check if any issues are high or critical severity."""
        return (
            self.overall_severity in [CritiqueSeverity.HIGH, CritiqueSeverity.CRITICAL]
            or any(
                i.severity in [CritiqueSeverity.HIGH, CritiqueSeverity.CRITICAL]
                for i in self.issues
            )
            or any(
                c.severity in [CritiqueSeverity.HIGH, CritiqueSeverity.CRITICAL]
                for c in self.contradictions
            )
        )

    def should_reject(self) -> bool:
        """Determine if the rule should be rejected based on critique."""
        return self.has_critical_issues() or (
            self.has_high_severity_issues() and len(self.issues) >= 3
        )

    def should_revise(self) -> bool:
        """Determine if the rule should be revised before acceptance."""
        return (
            not self.should_reject()
            and (len(self.issues) > 0 or len(self.edge_cases) > 0)
            and self.suggested_revision is not None
        )
